/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.1.0
 *
 * Project: '016_MilandrUART_USB' 
 * Target:  'Target_1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "MDR32F9Q2I.h"

/* Milandr::Device:Startup@2.2.0i */
/* Target microcontroller definition */
#define USE_MDR32F9Q2I


#endif /* RTE_COMPONENTS_H */
